services:
  postgres:
    image: postgres:16-alpine
    container_name: umlSoft
    restart: always
    environment:
      POSTGRES_USER: yimy
      POSTGRES_PASSWORD: tarqui231
      POSTGRES_DB: softDB
    ports:
      - "5432:5432"
    volumes:
      - ./database/postgres_data:/var/lib/postgresql/data
      - ./database/base.sql:/docker-entrypoint-initdb.d/base.sql